name: 'trimja action'
description: 'Download, setup, and runs trimja to reduce the size of your ninja build file'
author: 'Elliot Goodrich'
inputs:
  version:
    description: 'Version of trimja to install'
    default: '1.1.0'
  path:
    description: 'Path to the ninja build file'
    default: './build.ninja'
  build-configuration:
    description: 'Additional string to include in the cache that describes your build configuration'
    default: ''
  affected:
    description: 'List of additional files or build outputs to mark as affected'
    default: ''
  explain:
    description: 'Whether to pass --explain to trimja'
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/main.m.cjs'
  post: 'dist/post.m.cjs'
  post-if: success()
