name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  initial-testing:
    name: Checks if this action works
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./